services:
  php-fpm:
    build:
      context: .
      dockerfile: builds/php-fpm/Dockerfile
      args:
        - WWW_ROOT_DIR=${WWW_ROOT_DIR}
    volumes:
      - ${WWW_ROOT_DIR}:/var/www
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    volumes:
      - ${WWW_ROOT_DIR}:/var/www
      - ./configs/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: